image: python:3.6

stages:
  - test
  - deploy

all_tests:
  stage: test
  script:
    - rm -rf .venv
    - virtualenv -p /usr/bin/python3.6 .venv
    - chmod +x .venv/bin/activate
    - source .venv/bin/activate
    - pip install -r requirements.txt
    - python -m pytest
    - python -m mypy test/test_vizbuilder.py
    - python -m pep8 datapylot

deploy:
  stage: deploy
  script:
    - source .venv/bin/activate
    - gunicorn --bind 0.0.0.0:8282
